# NumPy Arrays

In [19]:
# a typical python list
regular_list = [1, 2, 3]

# note how Jupyter Notebook shows the last object returned
regular_list

[1, 2, 3]

In [20]:
# import the numpy module
import numpy as np

In [21]:
# convert the python list into a numpy vector (1D Array)
numpy_vector = np.array(regular_list)

numpy_vector

array([1, 2, 3])

In [22]:
# a typical python list of lists
regular_list_of_lists = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

regular_list_of_lists

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [23]:
# convert the python list of lists into a numpy matrix (2D Array)
numpy_matrix = np.array(regular_list_of_lists)

numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### NumPy Methods

In [24]:
# return a numpy Array from start, stop - 1 in incrementing order
print(np.arange(0, 10))

# return a numpy Array from start, stop - 1 based on the step size
print(np.arange(0, 10, 2))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [25]:
# return a numpy Array of zeros as a 1D Array using a constant size
print(np.zeros(3))
print()

# return a numpy Array of zeroes as a 2D Array using a tuple of row, column
print(np.zeros((2, 3)))

[0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]


In [26]:
# return of a numpy Array of ones (works the same as np.zeros)
print(np.ones(3)) # array([1., 1., 1.])
print()
print(np.ones((2, 3))) # array([[1., 1., 1.], [1., 1., 1.]])

[1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]]


In [27]:
# return a 1D numpy Array from start, stop with 11 evenly spaced points
np.linspace(0, 5, 11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [28]:
"""
return an identity matrix:
in linear algebra, a square matrix where the diagonal
consists of 1 and everything else consists of 0s
"""
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
"""
return a 1D Array with random values from 0 to a number less than 1 of size
"""
print(np.random.rand(5))

"""
return a 2D Array with random values from 0
to a number less than 1 of tuple row, column

unlike other methods, you do not need to pass a tuple
and only need to pass the size parameters into rand()
"""
print(np.random.rand(5, 5))

[0.38915506 0.32373701 0.75480141 0.03669155 0.58492481]
[[0.84428732 0.13135683 0.13550112 0.98774073 0.46224822]
 [0.99909203 0.91556992 0.91362088 0.82521564 0.61956775]
 [0.40149442 0.80340068 0.16788717 0.17820011 0.78403815]
 [0.99811427 0.60127409 0.29512001 0.11996248 0.28356253]
 [0.73431917 0.86922907 0.12887653 0.21684255 0.17493338]]


In [30]:
"""
return an Array with random values from a non-uniform distribution of
random values, uses a standard normal distribution/gaussian distribution
"""
print(np.random.randn(2))
print()
print(np.random.randn(4, 4))

[0.96698107 0.95314348]

[[-0.47628667  0.10887141  1.15014777 -0.6722314 ]
 [ 1.70653459  0.14455441 -1.08850514 -0.09574619]
 [-0.59498397  1.64527956 -0.27701283  0.30135324]
 [ 1.0874345   0.576935   -0.71498876 -0.91961853]]


In [31]:
# return a random integer between low, high - 1
print(np.random.randint(1, 100))

# return a 1D Array of size amount of random integers from low, high - 1
print(np.random.randint(1, 100, 10))

29
[59 25 53 94 31 93 30 37 68 61]


### Useful Attributes of a NumPy Array

In [32]:
# create a numpy Array from 0 to 9
arr = np.arange(10)
print(arr)
print()

# create a numpy Array of 10 random values randomly selected from 0 to 49
ranarr = np.random.randint(0, 50, 10)
print(ranarr)
print()

"""
return a re-shape of the arr Array with 2 rows and 5 columns
Note: row * column must equal the Array's size
"""
print(arr.reshape(2, 5))

[0 1 2 3 4 5 6 7 8 9]

[ 0  0 48  4 10  8  8 24 48 36]

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [33]:
# return the maximum value in an Array
print(ranarr.max())

# return the index of the maximum value in an Array (0-based indexing)
print(ranarr.argmax())

48
2


In [34]:
# return the minimum value in an Array
print(ranarr.min())

# return the index of the minimum value in an Array (0-based indexing)
print(ranarr.argmin())

0
0


In [35]:
# return the shape (dimensions) of an Array
print(ranarr.shape)
print(arr.shape)
print(arr.reshape(2, 5).shape)

(10,)
(10,)
(2, 5)


In [36]:
# return the data-types of an Array
arr.dtype

dtype('int32')